name: Python Code Quality and Lint

on:
  push:
    branches: code-quality
  pull_request:
    # The branches below must be a subset of the branches above
    branches: code-quality

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: WillCodeForCats/python-lint-action@master
        with:
          python-root-list: "custom_components/tekmar_482"
          use-flake8: true
          use-black: true
          use-isort: true
